name = "ABM4OSN"
uuid = "0e5fa1c2-265a-439b-98f5-e582845d2e65"
authors = ["Patrick Halbach", "Johannes Nakayama"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
